version: '3.7'

services:
  traefik:
    image: traefik:1.7-alpine
    command: -c /dev/null
      - "--api"
      - "--docker"
    ports:
      - "8080:8080"
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=wordpress
      - PMA_PASSWORD=wordpress
    labels:
      - traefik.frontend.rule=Host:pma.localhost
      - traefik.frontend.port=80
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - ${PWD}/.var/lib/mysql:/var/lib/mysql
    restart: always
    ports:
      - 33060:3306
  php:
    build: ./.docker/php-fpm
    ports:
      - "9000:9000"
    links:
      - db
    volumes:
      - ./bedrock:/var/www/wordpress:cached
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASS: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
  nginx:
    build: ./.docker/nginx
    links:
      - php
    volumes:
      - ./bedrock:/var/www/wordpress:cached
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    labels:
      - traefik.frontend.rule=Host:localhost
